name: Build and deploy ASP.Net Core app to Azure Web App - storonnimvTEST

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build StoronnimV.Server/StoronnimV.Api --configuration Release

      - name: dotnet publish
        run: dotnet publish StoronnimV.Server/StoronnimV.Api -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A015F3005CBC434190E5AC995FA590AF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BDE05A92A9454A3FA0F163437FC89C2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_803FC4E0FA7241E3AEC41E94ED64475E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'storonnimvTEST'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
